# Generated by Django 4.2.26 on 2025-11-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='찜한 날짜')),
            ],
            options={
                'verbose_name': '찜',
                'verbose_name_plural': '찜',
                'ordering': ['-created_at'],
            },
        ),
    ]
