# Generated by Django 4.2.26 on 2025-11-18 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_postings', '0001_initial'),
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='강사'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='job_postings.jobposting', verbose_name='공고'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['instructor', '-created_at'], name='favorites_f_instruc_913106_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('instructor', 'job_posting')},
        ),
    ]
