# Generated by Django 4.2.26 on 2025-11-18 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='academy',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'academy'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academy_reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='학원'),
        ),
        migrations.AddField(
            model_name='review',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='applications.application', verbose_name='지원'),
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='review',
            name='instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='강사'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['instructor', '-created_at'], name='reviews_rev_instruc_8f218a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['academy', '-created_at'], name='reviews_rev_academy_836709_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('academy__isnull', True), ('instructor__isnull', False)), models.Q(('academy__isnull', False), ('instructor__isnull', True)), _connector='OR'), name='review_target_check'),
        ),
    ]
