# Generated by Django 4.2.26 on 2025-11-18 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='verifications/', verbose_name='파일')),
                ('file_name', models.CharField(max_length=255, verbose_name='파일명')),
                ('file_size', models.PositiveIntegerField(verbose_name='파일 크기')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일')),
            ],
            options={
                'verbose_name': '인증 서류 파일',
                'verbose_name_plural': '인증 서류 파일',
            },
        ),
        migrations.CreateModel(
            name='InstructorVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '인증 대기'), ('approved', '인증 완료'), ('rejected', '인증 반려')], default='pending', max_length=20, verbose_name='상태')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='반려 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='검토일')),
                ('files', models.ManyToManyField(related_name='instructor_verifications', to='verifications.verificationfile', verbose_name='서류 파일')),
                ('instructor', models.OneToOneField(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_verification', to=settings.AUTH_USER_MODEL, verbose_name='강사')),
            ],
            options={
                'verbose_name': '강사 인증',
                'verbose_name_plural': '강사 인증',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademyVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '인증 대기'), ('approved', '인증 완료'), ('rejected', '인증 반려')], default='pending', max_length=20, verbose_name='상태')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='반려 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='검토일')),
                ('academy', models.OneToOneField(limit_choices_to={'role': 'academy'}, on_delete=django.db.models.deletion.CASCADE, related_name='academy_verification', to=settings.AUTH_USER_MODEL, verbose_name='학원')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academy_verification', to='verifications.verificationfile', verbose_name='사업자등록증')),
            ],
            options={
                'verbose_name': '학원 인증',
                'verbose_name_plural': '학원 인증',
                'ordering': ['-created_at'],
            },
        ),
    ]
