# Generated by Django 4.2.26 on 2025-11-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('application_accepted', '지원 합격'), ('application_rejected', '지원 불합격'), ('verification_approved', '인증 승인'), ('verification_rejected', '인증 반려'), ('new_posting', '새 공고 알림'), ('new_application', '새 지원 알림')], max_length=50, verbose_name='알림 유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('related_url', models.CharField(blank=True, max_length=500, verbose_name='관련 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_result', models.BooleanField(default=True, verbose_name='지원 결과 알림')),
                ('verification_result', models.BooleanField(default=True, verbose_name='인증 결과 알림')),
                ('new_posting', models.BooleanField(default=True, verbose_name='새 공고 알림')),
                ('marketing', models.BooleanField(default=False, verbose_name='마케팅 알림')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '알림 설정',
                'verbose_name_plural': '알림 설정',
            },
        ),
    ]
