# Generated by Django 4.2.26 on 2025-11-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '지원 완료'), ('reviewing', '검토중'), ('accepted', '최종 합격'), ('rejected', '불합격')], default='pending', max_length=20, verbose_name='상태')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='불합격 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='지원일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '지원',
                'verbose_name_plural': '지원',
                'ordering': ['-created_at'],
            },
        ),
    ]
