# Generated by Django 4.2.26 on 2025-11-18 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_postings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='강사'),
        ),
        migrations.AddField(
            model_name='application',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job_postings.jobposting', verbose_name='공고'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', '-created_at'], name='application_status_db7a61_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job_posting', 'status'], name='application_job_pos_c9417c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('instructor', 'job_posting')},
        ),
    ]
