# Generated by Django 4.2.26 on 2025-11-18 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('phone', models.CharField(max_length=20, verbose_name='전화번호')),
                ('role', models.CharField(choices=[('instructor', '강사'), ('academy', '학원'), ('admin', '관리자')], max_length=20, verbose_name='역할')),
                ('is_verified', models.BooleanField(default=False, verbose_name='인증 완료')),
                ('verification_status', models.CharField(choices=[('none', '미인증'), ('pending', '인증 대기'), ('approved', '인증 완료'), ('rejected', '인증 반려')], default='none', max_length=20, verbose_name='인증 상태')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입일')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'ordering': ['-date_joined'],
            },
        ),
    ]
