# Generated by Django 4.2.26 on 2025-11-18 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy_name', models.CharField(max_length=100, verbose_name='학원명')),
                ('academy_image', models.ImageField(blank=True, null=True, upload_to='academies/profile/', verbose_name='학원 이미지')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('operating_hours', models.CharField(blank=True, help_text='예: 09:00-18:00', max_length=50, verbose_name='운영 시간')),
                ('main_genres', models.JSONField(default=list, help_text='무용 장르 리스트', verbose_name='주요 장르')),
                ('description', models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='학원 소개')),
                ('facilities', models.JSONField(default=list, help_text='편의시설 리스트', verbose_name='편의시설')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='위도')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='경도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '학원 프로필',
                'verbose_name_plural': '학원 프로필',
            },
        ),
    ]
