# Generated by Django 4.2.26 on 2025-11-18 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100, verbose_name='학교명')),
                ('major', models.CharField(max_length=100, verbose_name='전공')),
                ('degree', models.CharField(choices=[('bachelor', '학사'), ('master', '석사'), ('doctor', '박사'), ('etc', '기타')], max_length=20, verbose_name='학위')),
                ('start_date', models.DateField(verbose_name='입학일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='졸업일')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '학력',
                'verbose_name_plural': '학력',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100, verbose_name='기관명')),
                ('position', models.CharField(max_length=50, verbose_name='직책')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '경력',
                'verbose_name_plural': '경력',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='instructors/profile/', verbose_name='프로필 이미지')),
                ('specialties', models.JSONField(default=list, help_text='무용 장르 리스트', verbose_name='전문 분야')),
                ('bio', models.TextField(blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='자기소개')),
                ('contact_visible', models.BooleanField(default=False, verbose_name='연락처 공개')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '강사 프로필',
                'verbose_name_plural': '강사 프로필',
            },
        ),
    ]
