# Generated by Django 4.2.26 on 2025-11-18 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='공고 제목')),
                ('region', models.CharField(choices=[('seoul', '서울'), ('gyeonggi', '경기'), ('incheon', '인천'), ('busan', '부산'), ('etc', '기타')], max_length=20, verbose_name='지역')),
                ('district', models.CharField(max_length=50, verbose_name='시/구')),
                ('genres', models.JSONField(default=list, help_text='무용 장르 리스트', verbose_name='무용 장르')),
                ('classes', models.CharField(blank=True, help_text='예: 초등반, 성인취미반', max_length=200, verbose_name='담당 수업')),
                ('work_days', models.JSONField(default=list, help_text='요일 리스트', verbose_name='근무 요일')),
                ('work_time', models.CharField(help_text='예: 14:00-18:00', max_length=50, verbose_name='근무 시간')),
                ('salary_type', models.CharField(choices=[('hourly', '시급'), ('monthly', '월급')], max_length=20, verbose_name='급여 유형')),
                ('salary', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='급여')),
                ('preferred_qualifications', models.TextField(blank=True, verbose_name='우대 사항')),
                ('description', models.TextField(verbose_name='상세 설명')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='위도')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='경도')),
                ('status', models.CharField(choices=[('draft', '작성중'), ('pending', '검토 대기'), ('active', '게시중'), ('closed', '마감'), ('hidden', '숨김'), ('deleted', '삭제')], default='pending', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '구인 공고',
                'verbose_name_plural': '구인 공고',
                'ordering': ['-created_at'],
            },
        ),
    ]
