# Generated by Django 4.2.26 on 2025-11-18 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_postings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='academy',
            field=models.ForeignKey(limit_choices_to={'role': 'academy'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL, verbose_name='학원'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['status', '-created_at'], name='job_posting_status_c97d84_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['region', 'district'], name='job_posting_region_c89a38_idx'),
        ),
    ]
